name: run flaky fixer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 1

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run tests with Maven
        run: |
          pwd
          mvn -version
          cd base
          mvn testrunner:testplugin
      - name: Commit files changed by tool
        if: always()
        run: |
          git config --global user.name 'Talank Baral'
          git config --global user.email 'talank@gces.edu.np'
          git add .
          git commit -m "[Robot]Automated report"
          git pull --rebase https://github.com/Talank/Mapper.git ${{ github.head_ref }}
          git push https://github.com/Talank/Mapper.git HEAD:${{ github.head_ref }}