name: run flaky fixer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 720

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run tests with Maven
        run: |
          pwd
          mvn -version
          cd base
          mvn testrunner:testplugin
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: Add flaky fix report files
          committer: Talank Baral <talank@gces.edu.np>
          body: |
            New report
            - Contains data generated by iFixFlakies tool
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          title: '[Report] Add flaky fix report files'
          milestone: 1
          branch: iFixFlakies-patches